services:
  - type: web
    name: kewl-game
    runtime: node
    plan: free
    buildCommand: npm install --include=prod --no-audit --no-fund
    startCommand: npm start
    envVars:
      - key: AUTH_SECRET
        generateValue: true
